# Generated by Django 5.0.1 on 2024-08-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0003_bill_delete_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='appointment',
        ),
        migrations.AddField(
            model_name='bill',
            name='days_stayed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='medicine_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='patient_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='patient_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='room_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
