# Generated by Django 5.0.1 on 2024-08-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0004_remove_bill_appointment_bill_days_stayed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
