# Generated by Django 5.0.1 on 2024-09-02 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0003_hospitalreport_average_appointment_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('PATIENTS', 'Patients Report'), ('DOCTORS', 'Doctors Report'), ('APPOINTMENTS', 'Appointments Report'), ('REVENUE', 'Revenue Report')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='HospitalReport',
        ),
    ]
