# Generated by Django 5.0.1 on 2024-08-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0002_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='working_hours',
            field=models.CharField(default='9:00 AM - 5:00 PM', max_length=255),
        ),
    ]
