# Generated by Django 5.0.1 on 2024-08-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0005_remove_doctor_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
